kumuluzee:
  name: bank-transactions
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/TransactionsDS
      connection-url: jdbc:postgresql://192.168.99.100:5433/transactions
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/TransactionsDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: transactions-endpoint
        url-pattern: /v1/transactions/*
rest-properties:
  healthy: true