kumuluzee:
  name: bank-transactions
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/BankDS
      connection-url: jdbc:postgresql://localhost:5432/bank
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379