kumuluzee:
  name: bank-transactions
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/TransactionsDS
      connection-url: jdbc:postgresql://192.168.99.100:5433/transactions
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/TransactionsDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: transactions-endpoint
        url-pattern: /v1/transactions/*
  streaming:
    kafka:
      consumer:
        bootstrap-servers: velomobile-01.srvs.cloudkafka.com:9094
        group-id: group1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="xtmm0ew0" password="Xq4ZWv7IqtqGroJAJgs45L0GTEbfB3Zv";'
        group-id: newer
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="transactions">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <!--<Socket name="logstash" host="85ebe26b-3a39-4754-8516-d8d6be2f154f-ls.logit.io"
                          port="21183"
                                                               protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>-->
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <!--<AppenderRef ref="logstash" level="trace"/>-->
                          </Root>
                      </Loggers>
                  </Configuration>'
rest-properties:
  healthy: true