apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-transactions-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-transactions
    spec:
      containers:
        - image: postgres:9.6.3
          name: postgres-transactions
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: transactions
          ports:
          - containerPort: 5432
            protocol: TCP