apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - image: rokplevel/bank-transactions
        name: transactions
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-transactions:5432/transaction
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.13.134:30477
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP